# This is a basic workflow to help you get started with Actions

name: Compile PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm install

      - name: Compile PDF with Marp
        run: |
          npm run build sponsorship-prospectus.md
          npm run build sponsorship-prospectus-ko.md

      - name: Compress PDF
        run: |
          sudo apt install -y ghostscript
          ps2pdf sponsorship-prospectus.pdf sponsorship-prospectus-compressed.pdf
          ps2pdf sponsorship-prospectus-ko.pdf sponsorship-prospectus-ko-compressed.pdf
          mkdir pdfs
          mv sponsorship-prospectus-compressed.pdf pdfs/
          mv sponsorship-prospectus-ko-compressed.pdf pdfs/
          

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: pdfs/*.pdf
          
          
